import type { PublicListing } from "./listingTypes";

/**
 * Source-approved featured inventory shown on the homepage. Public catalogue
 * pages and administrator-managed inventory still use the authenticated API;
 * keeping this compact source set local prevents a transient preview network
 * interruption from blocking the public homepage rendering.
 */
export const homeFeaturedProperties: PublicListing[] = [
  {
    id: -1,
    slug: "maple-residence",
    kind: "property",
    purpose: "sale",
    featured: true,
    title: "The Maple Residence",
    sourceTitle: "The Maple Residence",
    displayPrice: 450000000,
    location: "Banana Island, Lagos",
    city: "Lagos",
    description: "A statement contemporary villa on Banana Island, finished to the highest specification.",
    propertyType: "house",
    bedrooms: 4,
    bathrooms: 5,
    sizeSqm: "620 m²",
    rentPeriod: null,
    features: ["Infinity pool", "24/7 security", "Smart-home system"],
    make: null,
    model: null,
    vehicleYear: null,
    trim: null,
    color: null,
    mileageKm: null,
    vehicleCondition: null,
    youtubeVideoId: "aqz-KE-bpKQ",
    images: [{ url: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80", altText: "The Maple Residence" }],
  },
  {
    id: -2,
    slug: "horizon-gardens",
    kind: "property",
    purpose: "sale",
    featured: true,
    title: "Horizon Gardens Estate",
    sourceTitle: "Horizon Gardens Estate",
    displayPrice: 75000000,
    location: "Ibeju-Lekki, Lagos",
    city: "Lagos",
    description: "Prime dry land within a fast-appreciating estate corridor, ready for development.",
    propertyType: "land",
    bedrooms: null,
    bathrooms: null,
    sizeSqm: "1,000 m²",
    rentPeriod: null,
    features: ["C-of-O title", "Fenced estate", "Motorable road"],
    make: null,
    model: null,
    vehicleYear: null,
    trim: null,
    color: null,
    mileageKm: null,
    vehicleCondition: null,
    youtubeVideoId: null,
    images: [{ url: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1200&q=80", altText: "Horizon Gardens Estate" }],
  },
  {
    id: -3,
    slug: "meridian-plaza",
    kind: "property",
    purpose: "sale",
    featured: true,
    title: "Meridian Office Plaza",
    sourceTitle: "Meridian Office Plaza",
    displayPrice: 1200000000,
    location: "Central Business District, Abuja",
    city: "Abuja",
    description: "A Grade-A commercial office asset with dedicated parking and backup power.",
    propertyType: "commercial",
    bedrooms: null,
    bathrooms: null,
    sizeSqm: "3,200 m²",
    rentPeriod: null,
    features: ["8 floors", "Dedicated parking", "Backup power"],
    make: null,
    model: null,
    vehicleYear: null,
    trim: null,
    color: null,
    mileageKm: null,
    vehicleCondition: null,
    youtubeVideoId: null,
    images: [{ url: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200&q=80", altText: "Meridian Office Plaza" }],
  },
];
