import { CarFront, FileText, MessageSquare, type LucideIcon } from "lucide-react";
import { useState } from "react";
import { Link } from "wouter";
import { ListingsPage } from "@/pages/ListingsPage";
import { SiteFooter, SiteHeader } from "@/components/ghorizon/SiteChrome";
import { trpc } from "@/lib/trpc";

const expectations: [LucideIcon, string, string][] = [[CarFront, "Curated Vehicles", "A handpicked selection of premium and luxury cars, each inspected and verified."], [FileText, "Full Specifications", "Detailed specs, history and pricing — complete transparency on every listing."], [MessageSquare, "Easy Inquiries", "The same quick-inquiry and appointment tools you use for our properties."]];

export default function CarSalesPage() {
  const [email, setEmail] = useState("");
  const [notified, setNotified] = useState(false);
  const cars = trpc.listings.publicList.useQuery({ kind: "vehicle" });
  if (!cars.isLoading && cars.data?.length) return <ListingsPage kind="vehicle" />;
  return <div className="min-h-screen"><section className="relative flex min-h-[100svh] items-center overflow-hidden text-white"><img src="https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=2000&q=80" alt="Luxury car in dramatic lighting" className="absolute inset-0 h-full w-full object-cover" /><div className="absolute inset-0 bg-[linear-gradient(180deg,rgba(12,31,82,.55)_0%,rgba(12,31,82,.35)_40%,rgba(12,31,82,.75)_100%)]" /><SiteHeader overHero /><div className="relative mx-auto w-full max-w-7xl px-5 pb-20 pt-28 text-center lg:px-8"><span className="inline-flex rounded-full bg-[#c9a24b]/90 px-4 py-1.5 text-xs font-bold uppercase tracking-[.18em] text-[#0c1f52]">Coming Soon</span><h1 className="mx-auto mt-8 max-w-3xl font-display text-5xl font-semibold leading-[1.05] sm:text-6xl lg:text-7xl">A new road,<br />same <em className="not-italic text-[#c9a24b]">trusted name.</em></h1><p className="mx-auto mt-6 max-w-xl text-lg text-white/85">The G Horizon Car Sales division is on its way — curated premium vehicles, full specifications and the seamless inquiry experience you know from our real estate division.</p><form onSubmit={(event) => { event.preventDefault(); setNotified(true); }} className="mx-auto mt-10 flex max-w-md flex-col gap-3 sm:flex-row"><label className="sr-only" htmlFor="car-email">Email address</label><input id="car-email" type="email" required value={email} onChange={(event) => setEmail(event.target.value)} placeholder="Your email address" className="field flex-1 !border-white/25 !bg-white/10 !text-white placeholder:text-white/55" /><button className="shrink-0 bg-[#3b82f6] px-6 py-3 font-semibold text-white">Notify Me</button></form>{notified && <p className="mt-4 text-sm text-[#e7d6ac]">You&apos;re on the list — we&apos;ll let you know the moment we launch.</p>}</div></section><section className="bg-white px-5 py-20 lg:px-8 lg:py-28"><div className="mx-auto max-w-7xl"><div className="mx-auto mb-14 max-w-2xl text-center"><p className="eyebrow center justify-center">Phase 2</p><h2 className="mt-4 font-display text-4xl font-semibold text-[#0c1f52] lg:text-5xl">What to expect</h2></div><div className="grid gap-7 md:grid-cols-3">{expectations.map(([Icon, title, text]) => <article key={title} className="rounded-md border border-[#f3f4f6] p-8 text-center"><div className="mx-auto grid h-12 w-12 place-items-center rounded-sm bg-[#eff4ff] text-[#1e3a8a]"><Icon className="h-6 w-6" /></div><h3 className="mt-6 font-display text-xl font-semibold text-[#1e3a8a]">{title}</h3><p className="mt-3 leading-relaxed text-slate-600">{text}</p></article>)}</div><div className="mt-14 text-center"><p className="mb-6 text-slate-600">In the meantime, explore our real estate portfolio.</p><Link href="/properties" className="bg-[#1e3a8a] px-6 py-3 font-semibold text-white">Browse Properties</Link></div></div></section><SiteFooter /></div>;
}
