/**
 * The approved property catalogue published with the supplied G Horizon source
 * site. It is used only when the project has no administrator-managed approved
 * listings yet, preserving the original customer-facing experience without
 * turning pending submissions into public records.
 */
export const sourcePropertyCatalog = [
  { id: -1, slug: "maple-residence", kind: "property" as const, status: "approved", purpose: "sale" as const, featured: true, title: "The Maple Residence", sourceTitle: "The Maple Residence", displayPrice: 450000000, location: "Banana Island, Lagos", city: "Lagos", description: "A statement contemporary villa on Banana Island, featuring floor-to-ceiling glazing, a private infinity pool and a double-height reception. Finished to the highest specification with imported fittings throughout.", propertyType: "house" as const, bedrooms: 4, bathrooms: 5, sizeSqm: "620 m²", rentPeriod: null, features: ["Infinity pool", "24/7 security", "Smart-home system", "BQ + 2-car garage", "Fitted kitchen", "Solar backup"], make: null, model: null, vehicleYear: null, trim: null, color: null, mileageKm: null, vehicleCondition: null, youtubeVideoId: "aqz-KE-bpKQ", images: [{ url: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80", altText: "The Maple Residence" }] },
  { id: -2, slug: "horizon-gardens", kind: "property" as const, status: "approved", purpose: "sale" as const, featured: true, title: "Horizon Gardens Estate", sourceTitle: "Horizon Gardens Estate", displayPrice: 75000000, location: "Ibeju-Lekki, Lagos", city: "Lagos", description: "Prime, dry and fully fenced land within a fast-appreciating estate corridor. Governor’s Consent / C-of-O title, ready for immediate development.", propertyType: "land" as const, bedrooms: null, bathrooms: null, sizeSqm: "1,000 m²", rentPeriod: null, features: ["C-of-O title", "Fenced & gated estate", "Motorable road", "Dry land", "Instant allocation"], make: null, model: null, vehicleYear: null, trim: null, color: null, mileageKm: null, vehicleCondition: null, youtubeVideoId: null, images: [{ url: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1200&q=80", altText: "Horizon Gardens Estate" }] },
  { id: -3, slug: "meridian-plaza", kind: "property" as const, status: "approved", purpose: "sale" as const, featured: true, title: "Meridian Office Plaza", sourceTitle: "Meridian Office Plaza", displayPrice: 1200000000, location: "Central Business District, Abuja", city: "Abuja", description: "A Grade-A office tower over eight floors with dedicated parking, high-speed lifts and backup power — an institutional-quality commercial asset.", propertyType: "commercial" as const, bedrooms: null, bathrooms: null, sizeSqm: "3,200 m²", rentPeriod: null, features: ["8 floors", "Dedicated parking", "2 service lifts", "Backup power", "Fibre-ready"], make: null, model: null, vehicleYear: null, trim: null, color: null, mileageKm: null, vehicleCondition: null, youtubeVideoId: null, images: [{ url: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200&q=80", altText: "Meridian Office Plaza" }] },
  { id: -4, slug: "cedar-court", kind: "property" as const, status: "approved", purpose: "sale" as const, featured: false, title: "Cedar Court", sourceTitle: "Cedar Court", displayPrice: 280000000, location: "Maitama, Abuja", city: "Abuja", description: "An elegant five-bedroom detached home in Maitama with mature gardens, a family lounge and staff quarters, set on a quiet, tree-lined street.", propertyType: "house" as const, bedrooms: 5, bathrooms: 6, sizeSqm: "740 m²", rentPeriod: null, features: ["Mature garden", "Staff quarters", "Family lounge", "Fitted kitchen", "Ample parking"], make: null, model: null, vehicleYear: null, trim: null, color: null, mileageKm: null, vehicleCondition: null, youtubeVideoId: null, images: [{ url: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=1200&q=80", altText: "Cedar Court" }] },
  { id: -5, slug: "serenade-duplex", kind: "property" as const, status: "approved", purpose: "rent" as const, featured: true, title: "The Serenade Duplex", sourceTitle: "The Serenade Duplex", displayPrice: 25000000, location: "Lekki Phase 1, Lagos", city: "Lagos", description: "A beautifully finished four-bedroom duplex available for lease in Lekki Phase 1, with an open-plan living space, fitted kitchen and serviced compound.", propertyType: "house" as const, bedrooms: 4, bathrooms: 5, sizeSqm: "520 m²", rentPeriod: "year" as const, features: ["Serviced compound", "Fitted kitchen", "24/7 security", "Backup power", "Parking for 4"], make: null, model: null, vehicleYear: null, trim: null, color: null, mileageKm: null, vehicleCondition: null, youtubeVideoId: "aqz-KE-bpKQ", images: [{ url: "https://images.unsplash.com/photo-1568605114967-8130f3a36994?auto=format&fit=crop&w=1200&q=80", altText: "The Serenade Duplex" }] },
  { id: -6, slug: "vantage-retail", kind: "property" as const, status: "approved", purpose: "rent" as const, featured: false, title: "Vantage Retail Suites", sourceTitle: "Vantage Retail Suites", displayPrice: 18000000, location: "Victoria Island, Lagos", city: "Lagos", description: "Flexible ground-floor retail and office suites for lease on Victoria Island — high footfall, excellent frontage and generous parking.", propertyType: "commercial" as const, bedrooms: null, bathrooms: null, sizeSqm: "1,100 m²", rentPeriod: "year" as const, features: ["Prime frontage", "12 configurable units", "High footfall", "Ample parking", "Backup power"], make: null, model: null, vehicleYear: null, trim: null, color: null, mileageKm: null, vehicleCondition: null, youtubeVideoId: null, images: [{ url: "https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1200&q=80", altText: "Vantage Retail Suites" }] },
];

export function filterSourceProperties(filters: {
  purpose?: "sale" | "rent";
  propertyType?: "land" | "house" | "apartment" | "commercial";
  city?: string;
  minPrice?: number;
  maxPrice?: number;
  query?: string;
}) {
  return sourcePropertyCatalog.filter((listing) => {
    if (filters.purpose && listing.purpose !== filters.purpose) return false;
    if (filters.propertyType && listing.propertyType !== filters.propertyType) return false;
    if (filters.city && listing.city !== filters.city) return false;
    if (filters.minPrice !== undefined && listing.displayPrice < filters.minPrice) return false;
    if (filters.maxPrice !== undefined && listing.displayPrice > filters.maxPrice) return false;
    const query = filters.query?.toLowerCase().trim();
    return !query || `${listing.title} ${listing.location}`.toLowerCase().includes(query);
  });
}
