import { useEffect, useState } from "react";
import { Bath, BedDouble, CarFront, ImageOff, MapPin, Ruler, ArrowUpRight } from "lucide-react";
import { Link } from "wouter";
import { type PublicListing, priceLabel } from "@/lib/listingTypes";

export function ListingCard({ listing }: { listing: PublicListing }) {
  const href = listing.kind === "property" ? `/properties/${listing.slug}` : `/cars/${listing.slug}`;
  const purpose = listing.purpose === "lease" ? "For lease" : listing.purpose === "let" ? "To let" : listing.purpose === "rent" ? "For rent" : "For sale";
  const imageUrl = listing.images[0]?.url;
  const [imageState, setImageState] = useState<"loading" | "loaded" | "failed">(imageUrl ? "loading" : "failed");
  useEffect(() => setImageState(imageUrl ? "loading" : "failed"), [imageUrl]);
  return <Link href={href} className="group block overflow-hidden border border-slate-200 bg-white transition duration-300 hover:-translate-y-1.5 hover:border-transparent hover:shadow-2xl hover:shadow-blue-950/15"><div className="relative aspect-[4/3] overflow-hidden bg-[#eef3fa]">{imageState === "loading" && <div className="absolute inset-0 animate-pulse bg-gradient-to-br from-slate-100 via-white to-slate-200" />}{imageState === "failed" && <div className="absolute inset-0 grid place-items-center text-center text-slate-500"><span><ImageOff className="mx-auto h-6 w-6 text-[#7183a6]" /><span className="mt-2 block text-xs font-semibold">Photo coming soon</span></span></div>}{imageUrl && imageState !== "failed" ? <img src={imageUrl} alt={listing.images[0]?.altText ?? listing.title} loading="lazy" decoding="async" onLoad={() => setImageState("loaded")} onError={() => setImageState("failed")} className={`h-full w-full object-cover transition duration-700 group-hover:scale-105 ${imageState === "loaded" ? "opacity-100" : "opacity-0"}`} /> : null}<span className="absolute left-4 top-4 bg-[#1e3a8a] px-3 py-1.5 text-[10px] font-bold uppercase tracking-[0.14em] text-white">{purpose}</span></div><div className="p-5"><div className="flex items-start justify-between gap-3"><p className="font-display text-2xl leading-tight text-[#0c1f52]">{listing.title}</p><ArrowUpRight className="mt-1 h-4 w-4 shrink-0 text-[#3b82f6]" /></div><p className="mt-2 flex items-center gap-1.5 text-sm text-slate-500"><MapPin className="h-3.5 w-3.5" />{listing.location}</p><p className="mt-5 text-lg font-bold text-[#1e3a8a]">{priceLabel(listing)}</p><div className="mt-5 flex flex-wrap gap-x-4 gap-y-2 border-t border-slate-100 pt-4 text-xs font-medium text-slate-500">{listing.kind === "property" ? <><span className="inline-flex items-center gap-1"><BedDouble className="h-3.5 w-3.5" />{listing.bedrooms ?? "—"} beds</span><span className="inline-flex items-center gap-1"><Bath className="h-3.5 w-3.5" />{listing.bathrooms ?? "—"} baths</span><span className="inline-flex items-center gap-1"><Ruler className="h-3.5 w-3.5" />{listing.sizeSqm ?? "—"}</span></> : <><span className="inline-flex items-center gap-1"><CarFront className="h-3.5 w-3.5" />{listing.vehicleYear ?? "—"}</span><span>{listing.make} {listing.model}</span><span>{listing.mileageKm ? `${listing.mileageKm.toLocaleString()} km` : listing.vehicleCondition?.replaceAll("_", " ")}</span></>}</div></div></Link>;
}
