import { Menu, X } from "lucide-react";
import { Link, useLocation } from "wouter";
import { useState } from "react";
import { cn } from "@/lib/utils";

const links = [["Products", "/properties"], ["About", "/about"], ["Services", "/services"], ["Consulting", "/contact"], ["FAQ", "/faq"], ["Car Sales", "/cars"]] as const;

export function SiteHeader({ overHero = false }: { overHero?: boolean }) {
  const [mobileOpen, setMobileOpen] = useState(false);
  const [location] = useLocation();
  const active = (href: string) => location === href || (href !== "/" && location.startsWith(`${href}/`));
  const nav = <>{links.map(([label, href]) => <Link key={href} href={href} onClick={() => setMobileOpen(false)} className={cn("relative text-sm font-medium transition hover:text-white", active(href) && "after:absolute after:-bottom-1 after:left-0 after:h-0.5 after:w-full after:bg-[#3b82f6]")}>{label}{label === "Car Sales" && <span className="ml-1.5 rounded-full bg-[#e7d6ac] px-1.5 py-0.5 text-[8px] font-bold uppercase tracking-wider text-[#7a5f1e]">Soon</span>}</Link>)}</>;
  return <header className={cn("z-40 w-full", overHero ? "absolute inset-x-0 top-0 px-6 pt-6 md:px-12 lg:px-16" : "sticky top-0 bg-[#0c1f52]") }><div className={cn("mx-auto flex items-center justify-between text-white", overHero ? "liquid-glass max-w-none rounded-xl px-4 py-2" : "h-[72px] max-w-7xl px-5 lg:px-8")}><Link href="/" className="text-xl font-semibold tracking-tight">G&nbsp;Horizon</Link><nav className="hidden items-center gap-8 lg:flex">{nav}</nav><div className="flex items-center gap-2"><Link href="/contact" className="hidden rounded-lg bg-white px-6 py-2 text-sm font-medium text-black transition hover:bg-slate-100 sm:inline-flex">Book a Consultation</Link><button onClick={() => setMobileOpen((value) => !value)} aria-label="Open menu" aria-expanded={mobileOpen} className="p-2 text-white lg:hidden">{mobileOpen ? <X className="h-5 w-5" /> : <Menu className="h-5 w-5" />}</button></div></div>{mobileOpen && <div className={cn("mx-auto mt-2 rounded-xl text-white lg:hidden", overHero ? "liquid-glass" : "bg-[#0c1f52]")}><nav className="flex flex-col gap-1 px-5 py-4">{nav}<Link href="/contact" onClick={() => setMobileOpen(false)} className="mt-3 rounded-lg bg-white px-6 py-2.5 text-center text-sm font-medium text-black">Book a Consultation</Link></nav></div>}</header>;
}

export function SiteFooter() {
  return <footer className="overflow-hidden bg-[#f9f9fb] px-4 pb-0 pt-16 md:pt-24"><div className="mx-auto w-full max-w-6xl"><div className="overflow-hidden rounded-[48px] border border-slate-200 bg-[#e9ebee] shadow-sm"><div className="m-2 rounded-[40px] bg-white shadow-sm"><div className="grid gap-12 p-8 md:grid-cols-2 md:p-10 lg:grid-cols-5 lg:p-12"><div className="space-y-8 lg:col-span-2"><div className="flex items-center gap-2.5"><span className="grid h-8 w-8 place-items-center rounded-[8px] bg-[#1e3a8a] font-display text-lg font-semibold leading-none text-white">G</span><span className="text-[26px] font-bold tracking-tight text-slate-900">G Horizon</span></div><p className="max-w-[320px] text-[16px] leading-relaxed text-slate-500">Premium real estate sourcing, sales and bespoke consultancy designed to elevate where you live, work and invest.</p><div className="flex gap-3"><a href="#" aria-label="LinkedIn" className="footer-social">in</a><a href="#" aria-label="Twitter" className="footer-social">𝕏</a><a href="#" aria-label="Instagram" className="footer-social">◎</a></div></div><FooterGroup title="Explore" links={[["Properties", "/properties"], ["Services", "/services"], ["Car Sales", "/cars"], ["FAQ", "/faq"]]} /><FooterGroup title="Company" links={[["About Us", "/about"], ["Careers", "#"], ["Partners", "#"]]} /><FooterGroup title="Connect" links={[["Contact Us", "/contact"], ["Book a Visit", "/contact"], ["hello@ghorizon.com", "mailto:hello@ghorizon.com"]]} /></div></div><div className="flex flex-col items-center justify-between gap-6 px-6 py-5 text-[15px] font-medium text-slate-500 md:flex-row md:px-16"><p>© 2026 G Horizon Enterprise Limited. All rights reserved.</p><div className="flex items-center gap-8"><a href="#">Legal Center</a><span className="h-4 w-px bg-slate-300" /><a href="#">User Agreement</a></div></div></div></div><div className="flex w-full items-center justify-center overflow-hidden"><p className="whitespace-nowrap px-4 text-[min(17vw,220px)] font-bold leading-none tracking-tight text-white/90">G Horizon</p></div></footer>;
}

function FooterGroup({ title, links }: { title: string; links: [string, string][] }) {
  return <div className="space-y-6"><h2 className="text-[14px] font-medium text-slate-400">{title}</h2><div className="grid gap-4">{links.map(([label, href]) => href.startsWith("/") ? <Link href={href} key={label} className="text-[15px] font-medium text-slate-800 hover:text-[#3b82f6]">{label}</Link> : <a href={href} key={label} className="text-[15px] font-medium text-slate-800 hover:text-[#3b82f6]">{label}</a>)}</div></div>;
}
