import { LogOut, Menu, PanelLeftClose, PanelLeftOpen } from "lucide-react";
import { useState } from "react";
import { Link, useLocation } from "wouter";
import { useAuth } from "@/_core/hooks/useAuth";
import { cn } from "@/lib/utils";

export type DashboardNavigationItem = { icon: React.ComponentType<{ className?: string }>; label: string; path: string };

export default function DashboardLayout({ children, title = "G Horizon Admin", navigation }: { children: React.ReactNode; title?: string; navigation: DashboardNavigationItem[] }) {
  const [expanded, setExpanded] = useState(true);
  const [location] = useLocation();
  const { user, logout } = useAuth();
  return <div className="min-h-screen bg-slate-50 md:flex"><aside className={cn("sticky top-0 hidden min-h-screen shrink-0 bg-[#0c1f52] text-white transition-all md:flex md:flex-col", expanded ? "w-64" : "w-[76px]")}><div className="flex h-[74px] items-center gap-3 border-b border-white/10 px-5"><button onClick={() => setExpanded((value) => !value)} aria-label="Toggle navigation" className="text-white/70 hover:text-white">{expanded ? <PanelLeftClose className="h-5 w-5" /> : <PanelLeftOpen className="h-5 w-5" />}</button>{expanded && <span className="font-display text-2xl">{title}</span>}</div><nav className="flex-1 space-y-1 px-3 py-6">{navigation.map(({ icon: Icon, label, path }) => <Link href={path} key={path} className={cn("flex items-center gap-3 px-3 py-3 text-sm font-medium transition", location === path ? "bg-white text-[#1e3a8a]" : "text-white/70 hover:bg-white/10 hover:text-white") }><Icon className="h-4 w-4 shrink-0" />{expanded && label}</Link>)}</nav><div className="border-t border-white/10 p-3"><Link href="/" className="mb-3 flex items-center gap-3 px-3 py-2 text-xs font-semibold text-white/60 hover:text-white">{expanded && "View public site ↗"}</Link><div className="flex items-center gap-3 px-3 py-3"><span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-[#c9a24b] text-sm font-bold text-[#0c1f52]">{user?.name?.slice(0, 1).toUpperCase() ?? "A"}</span>{expanded && <span className="min-w-0 flex-1"><span className="block truncate text-sm font-semibold">{user?.name ?? "Administrator"}</span><span className="block truncate text-xs text-white/60">{user?.email ?? ""}</span></span>}<button onClick={() => logout()} aria-label="Sign out" className="text-white/70 hover:text-white"><LogOut className="h-4 w-4" /></button></div></div></aside><div className="flex-1"><header className="sticky top-0 z-20 flex h-[64px] items-center justify-between border-b border-slate-200 bg-white px-5 md:hidden"><span className="font-display text-2xl text-[#0c1f52]">G Horizon Admin</span><Link href="/" aria-label="View public site"><Menu className="h-5 w-5 text-[#1e3a8a]" /></Link></header><main className="p-5 sm:p-8">{children}</main></div></div>;
}
